language: r
r:
  - release

cache: packages

sudo: required

dist: trusty

warnings_are_errors: true

r_packages:
  - roxygen2
  - rmarkdown
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
